version: '3.8'
services:
  pgdb:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: rootdb
      POSTGRES_PASSWORD: rootdb
      POSTGRES_DB: rootdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer:1.21.0-p1
    restart: unless-stopped
    ports:
      - "6432:6432"
    depends_on:
      - pgdb
    volumes:
      - ./config/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./config/userlist.txt:/etc/pgbouncer/userlist.txt
