version: '3.8'
services:
  pgdb:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    # expose:
    #   - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    # environment:
    #   DB_USER: root
    #   DB_PASSWORD: root
    #   DB_HOST: pgdb
    #   DB_NAME: rootdb
    #   POOL_MODE: session
    #   ADMIN_USERS: postgres,root
      # AUTH_TYPE: scram-sha-256
    ports:
      - "6432:6432"
    depends_on:
      - pgdb
    volumes:
      - ./config/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./config/userlist.txt:/etc/pgbouncer/userlist.txt:ro
